### ISSUE TITLE
Zonas

### ISSUE THREAD

**Issue by acralkmim** [mapaslivres/zonas-eleitorais#3]

**Comment by vgeorge** [comment]
Olá @acralkmim, você tem alguma questão?

**Comment by acralkmim** [comment]
Olá. Não descobri ainda um mapa das zonas eleitorais. Mas o seu arquivo me deu a ideia de geolocalizar os Ceps dos locais de votação. Você já fez isso?

**Comment by vgeorge** [comment]
Na época em que criei este repositório não havia dados consolidados e georreferencidos, mas agora você pode encontrar todos os locais de votação com coordenadas aqui:

https://dadosabertos.tse.jus.br/dataset/eleitorado-atual

**Comment by acralkmim** [comment]
Muitíssimo obrigado.
